# Generated by Django 5.0.2 on 2024-02-17 14:38

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('store', '0002_alter_product_options'), ('store', '0003_alter_product_options_alter_store_options')]

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'permissions': [('view_store_products', 'Can view store products'), ('view_store_managers', 'Can view store managers')], 'verbose_name': 'Store', 'verbose_name_plural': 'Stores'},
        ),
    ]
